name: build.yml

on:
  workflow_call:
    inputs:
      output-path:
        required: true
        type: string

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup target add x86_64-unknown-linux-gnu
      - run: |
          mkdir -p ${output_name}/lin_x64
          cargo build --target x86_64-unknown-linux-gnu --release
          cp target/x86_64-unknown-linux-gnu/release/lib${output_name}.so ${output_name}/lin_x64/${output_name}.xpl
        env:
          output_name: ${{ inputs.output-path }}
      - uses: actions/upload-artifact@v4
        with:
          name: lin_x64
          path: ${{ inputs.output-path }}

  build_macos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin
      - run: |
          mkdir -p ${output_name}/mac_x64
          cargo build --target aarch64-apple-darwin --release
          cargo build --target x86_64-apple-darwin --release
          llvm-lipo -create -output ${output_name}/mac_x64/${output_name}.xpl target/aarch64-apple-darwin/release/lib${output_name}.dylib target/x86_64-apple-darwin/release/lib${output_name}.dylib
        env:
          output_name: ${{ inputs.output-path }}
      - uses: actions/upload-artifact@v4
        with:
          name: mac_x64
          path: ${{ inputs.output-path }}

  build_windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup target add x86_64-pc-windows-gnu
      - run: |
          mkdir -p ${output_name}/win_x64
          cargo build --target x86_64-pc-windows-gnu --release
          cp target/x86_64-pc-windows-gnu/release/${output_name}.dll ${output_name}/win_x64/${output_name}.xpl
        env:
          output_name: ${{ inputs.output-path }}
      - uses: actions/upload-artifact@v4
        with:
          name: win_x64
          path: ${{ inputs.output-path }}

  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p ${{ inputs.output-path }}
          cp LICENSE ${{ inputs.output-path }}/LICENSE.txt
          cp README.md ${{ inputs.output-path }}/README.md
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ${{ inputs.output-path }}
