name: publish.yml

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      output-path: tweaks

  release:
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/_release.yml
    with:
      output-path: tweaks
